# Generated by Django 4.1.2 on 2022-11-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cenaBrutto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cenaNetto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Opakowanie',
            fields=[
                ('produkt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebApp.produkt')),
                ('iloscProduktu', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('WebApp.produkt',),
        ),
        migrations.CreateModel(
            name='Magazym',
            fields=[
                ('opakowanie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebApp.opakowanie')),
            ],
            bases=('WebApp.opakowanie',),
        ),
    ]
