# Generated by Django 4.1.2 on 2022-11-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('opakowanie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebApp.opakowanie')),
                ('idMagazynu', models.IntegerField(default=0)),
            ],
            bases=('WebApp.opakowanie',),
        ),
        migrations.AddField(
            model_name='opakowanie',
            name='idPudelka',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produkt',
            name='nazwaProduktu',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='produkt',
            name='stawkaVat',
            field=models.CharField(choices=[('A', '23%'), ('B', '5%'), ('C', '0%'), ('d', 'Nie dotyczy')], default=' ', max_length=3),
        ),
        migrations.AddField(
            model_name='produkt',
            name='typIlosci',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.DeleteModel(
            name='Magazym',
        ),
    ]
