# Generated by Django 4.1.4 on 2022-12-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazyn',
            name='nrOpakowania',
        ),
        migrations.AddField(
            model_name='opakowanie',
            name='magazyn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='WebApp.magazyn'),
        ),
        migrations.AlterField(
            model_name='opakowanie',
            name='towar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='WebApp.produkt'),
        ),
    ]
