# Generated by Django 4.1.4 on 2023-01-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_opakowanie_idpudelka'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentPrzyjecia',
            fields=[
                ('NrDokumentu', models.IntegerField(primary_key=True, serialize=False)),
                ('sumaBrutto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sumaNetto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Przyjęcie',
            },
        ),
        migrations.CreateModel(
            name='DokumentWydania',
            fields=[
                ('NrDokumentu', models.IntegerField(primary_key=True, serialize=False)),
                ('sumaBrutto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sumaNetto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Wydanie',
            },
        ),
        migrations.AlterModelOptions(
            name='magazyn',
            options={'verbose_name_plural': 'Magazyny'},
        ),
        migrations.AlterModelOptions(
            name='opakowanie',
            options={'verbose_name_plural': 'Opakowania'},
        ),
        migrations.AlterModelOptions(
            name='produkt',
            options={'verbose_name_plural': 'Produkty'},
        ),
    ]
