# Generated by Django 4.1.4 on 2023-01-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_dokumentprzyjecia_dokumentwydania_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('NrDokumentu', models.IntegerField(primary_key=True, serialize=False)),
                ('sumaBrutto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sumaNetto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('typ', models.CharField(choices=[('Dostawa', 'Dostawa'), ('Wydanie', 'Wydanie')], default=' ', max_length=10)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Przyjęcie',
            },
        ),
        migrations.DeleteModel(
            name='DokumentPrzyjecia',
        ),
        migrations.DeleteModel(
            name='DokumentWydania',
        ),
    ]
