# Generated by Django 4.1.4 on 2023-01-10 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_dokument_delete_dokumentprzyjecia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokument',
            options={'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.AlterField(
            model_name='dokument',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
